apiVersion: v1
baseDomain: demo.net 
controlPlane: 
  hyperthreading: Enabled   
  name: master
  platform:
    aws:
      zones:
      - ap-southeast-1
      - ap-southeast-1b
      - ap-southeast-1c
      rootVolume:
        iops: 4000
        size: 500
        type: io1
      type: m5a.xlarge 
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    aws:
      type: m5a.large
      zones:
      - ap-southeast-1
      - ap-southeast-1b
      - ap-southeast-1c
  replicas: 3
metadata:
  name: testcluster 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: ap-southeast-1 
    userTags:
      adminContact: jsmith
      costCenter: 7536
    subnets: 
    - subnet-0fba30a018528e31d # ap-southeast-1-private
    - subnet-06db840ed48a53357 # ap-southeast-1b-private
    - subnet-0e4970787c4158ac9 # ap-southeast-1c-private
    - subnet-0d9f496b3fed4a3ed # ap-southeast-1-public
    - subnet-0af54dbcd65a8febd # ap-southeast-1b-public
    - subnet-04756f2eccb69ef28 # ap-southeast-1c-public
pullSecret: '{"auths": ...}' 
fips: false 
sshKey: ssh-ed25519 AAAA... 